### ISSUE TITLE
Deploy update for WebIDE

### ISSUE THREAD

**Issue by jryans** [mozilla/mortar-privileged-remote-app#13]
Now that this and mozilla/mortar-privileged-empty-app#1 are resolved, what's needed to deploy them so that WebIDE sees the changes?

I assume some kind of CDN upload and editing the templates list perhaps?

@sole, any ideas?

**Comment by sole** [comment]
This is done using https://github.com/sole/mortar-devtools

First the git modules need to be updated to the desired version, then the `build.js` script can be run to generate the `dist` folder that has to be uploaded to the CDN.

Only a few people can upload to the CDN right now - it's @potch, @fwenzel and me IIRC.

Paul mentioned we should probably move to using the same FTP you're using for the simulators because we would get way less issues with cache expiration times etc.

Perhaps this should be a good moment to reconsider this... or maybe after the workweek?
